@startuml 惑星のモデル
object 宇宙

object 宇宙の構造
note top: 宇宙の大規模構造

object 超空洞
object 銀河フィラメント
object 超銀河団
object 銀河団
object 銀河
object 星団
object 恒星
宇宙 -- 宇宙の構造
宇宙の構造 *-- 超空洞
宇宙の構造 *-- 銀河フィラメント
銀河フィラメント *-- 超銀河団
超銀河団 *-- 銀河団
銀河団 *-- 銀河
銀河 *-- 星団
星団 *-- 恒星

object 宇宙の成分
object ダークエネルギー
object ダークマター
object 原子
宇宙 -- 宇宙の成分
宇宙の成分 *-- ダークエネルギー
宇宙の成分 *-- ダークマター
宇宙の成分 *-- 原子

object 宇宙空間
object 宇宙空間の定義
object 国際航空連盟の定義
object アメリカ空軍の定義
宇宙 -- 宇宙空間
宇宙空間 <.. 宇宙空間の定義: 定義する
宇宙空間の定義 <|-- 国際航空連盟の定義
宇宙空間の定義 <|-- アメリカ空軍の定義

object 宇宙論
object 宗教
object 哲学
object 天文学
object 現代宇宙論
object 宇宙工学
宇宙 -- 宇宙論
宇宙論 <|-- 宗教
宇宙論 <|-- 哲学
宇宙論 <|-- 天文学
宇宙論 <|-- 現代宇宙論
宇宙論 <|-- 宇宙工学
宇宙の成分 <.. 現代宇宙論: 観測する
宇宙空間の定義 <. 宇宙工学: 設ける
@enduml
