@startuml 自転車のモデル
object 自転車 {
  drive(乗り手)
}
object 乗り手
乗り手 -- 自転車

object フレーム
object 車輪
object ハンドル
object サドル
object ペダル
object ドライブトレイン
object ブレーキ

自転車 *-- フレーム
自転車 *-- "2" 車輪
自転車 *-- ハンドル
自転車 *-- サドル
自転車 *-- ペダル
自転車 *-- ドライブトレイン
自転車 *-- ブレーキ

object アクセサリー
object 前照灯
object 鍵
アクセサリー <|-- 前照灯
アクセサリー <|-- 鍵
自転車 o- "0..*" アクセサリー

object 道路交通法
object 夜間点灯の義務
object ブレーキを備える義務
道路交通法 <|-- 夜間点灯の義務
道路交通法 <|-- ブレーキを備える義務
道路交通法 .> 自転車 : 満たしている
@enduml
