@startuml 野球のモデル
object 試合
object 公認野球規則
試合 -- 公認野球規則

object 野球場
試合 *-- 野球場

object 審判員
試合 *-- 審判員

object チーム
object 目的
note right: より多くの得点を得て、勝つこと
チーム -- 目的
チーム "2" --* "1" 試合
目的 -- 公認野球規則: 明記されている

object チーム編成
object チーム編成ルール
object 監督
object コーチ
object 出場選手
object 控え選手
チーム -- チーム編成
チーム編成ルール .> チーム編成: 満たしている
チーム編成 *-- 監督
チーム編成 *-- コーチ
チーム編成 *-- 出場選手
チーム編成 *-- 控え選手
出場選手 - 控え選手: 交代可能

object 守備位置
出場選手 -- 守備位置
@enduml
