@startuml 将棋のモデル
object 対局者
object 席次
object 上座
object 下座

対局者 *-- 席次
席次 <|-- 上座
席次 <|-- 下座

object 将棋盤
object マス {
  座標
}
object 陣地
object 自陣
object 敵陣
将棋盤 "1" *-- "81" マス
マス -- 陣地
陣地 <|-- 自陣
陣地 <|-- 敵陣
陣地 -- 対局者

object 将棋駒
object 玉将
object 王将
object 飛車
object 角行
object 金将
object 銀将
object 桂馬
object 香車
object 歩兵
将棋駒 <|-- 玉将
将棋駒 <|-- 王将
将棋駒 <|-- 飛車
将棋駒 <|-- 角行
将棋駒 <|-- 金将
将棋駒 <|-- 銀将
将棋駒 <|-- 桂馬
将棋駒 <|-- 香車
将棋駒 <|-- 歩兵

マス "1" -- "0..1" 将棋駒: 配置される
object 成駒
飛車 ..|> 成駒
角行 ..|> 成駒
銀将 ..|> 成駒
桂馬 ..|> 成駒
香車 ..|> 成駒
歩兵 ..|> 成駒
敵陣 -- 成駒: 移動前後のマスが敵陣内だった場合、成ることができる
@enduml
