@startuml 旅行予約のモデル
object 顧客 {
  名前
  連絡先
}
object 予約 {
  予約日
  ステータス
  /料金
}
note top: 導出ルール：\n/料金 = サービスの料金の合計

object 料金支払い {
  日時
}

object 旅程 {
  /開始日
  /終了日
}
note top: 導出ルール：\n/開始日 = サービスの中で最も早い開始日時の日付\n/終了日 = サービスの中で最も遅い終了日時の日付

object サービス {
  料金
  開始日時
  終了日時
}
object 宿泊
object 交通
object アクティビティ

顧客 "1" - "*" 予約
予約 "1" -- "0..1" 料金支払い
予約 "1" - "1" 旅程
旅程 "1" -- "1..*" サービス

サービス <|-- 宿泊
サービス <|-- 交通
サービス <|-- アクティビティ

@enduml
