@startuml カレーライスのモデル
object カレーライス

object カレールー
object 小麦粉
object 具材
object 出汁
object カレー粉
object スパイス
object スパイス配合
note right: カレーらしい風味や色の配合

カレー粉 <.. スパイス配合
スパイス配合 --- スパイス

カレールー *-- カレー粉
カレールー *-- 小麦粉
カレールー *-- 具材
カレールー *-- 出汁

object 野菜
object 肉
object 魚介

具材 <|-- 野菜
具材 <|-- 肉
具材 <|-- 魚介

object ライス
object ジャポニカ米
object インディカ米
ライス <|-- ジャポニカ米
ライス <|-- インディカ米

object 付け合せ
object 福神漬け
object らっきょう
付け合せ <|-- 福神漬け
付け合せ <|-- らっきょう

object 皿

カレーライス *-- カレールー
カレーライス *-- ライス
カレーライス *-- 付け合せ
カレーライス *-- 皿
@enduml
