@startuml コーヒーのモデル
object コーヒーノキ
object 精製
object 精製方法
object 乾式
object 湿式
object 生豆
object 等級

精製方法 <|-- 乾式
精製方法 <|-- 湿式
精製 <. 精製方法 : 実行する
精製 -- コーヒーノキ
生豆 <.. 精製 : 生成する
生豆 *- 等級

object 焙煎
object 焙煎方法
object 直火
object 熱風
object 遠赤外線
object マイクロ波
object 過熱水蒸気
object 焙煎豆
object 焙煎度

焙煎方法 <|-- 直火
焙煎方法 <|-- 熱風
焙煎方法 <|-- 遠赤外線
焙煎方法 <|-- マイクロ波
焙煎方法 <|-- 過熱水蒸気
焙煎 <. 焙煎方法 : 実行する
焙煎 -- 生豆
焙煎豆 <.. 焙煎 : 生成する
焙煎豆 *- 焙煎度

object 粉砕
object 粉砕粒子度合い
object 粉末

粉砕 -- 焙煎豆
粉末 <.. 粉砕 : 生成する
粉末 *- 粉砕粒子度合い

object 抽出
object 抽出方法
object 濾過
object 煮沸後濾過
object 煮沸
object 浸漬
object コーヒー

抽出方法 <|-- 濾過
抽出方法 <|-- 煮沸後濾過
抽出方法 <|-- 煮沸
抽出方法 <|-- 浸漬
抽出 <. 抽出方法 : 実行する
抽出 -- 粉末
コーヒー <.. 抽出 : 生成する
@enduml
