@startuml 試験性のモデル
object 保守性

object 試験性
保守性 *-- 試験性

object 実行円滑性
object 観測容易性
object 制御容易性
object 分解容易性
object 単純性
object 安定性
object 理解容易性
試験性 *-- 実行円滑性
試験性 *-- 観測容易性
試験性 *-- 制御容易性
試験性 *-- 分解容易性
試験性 *-- 単純性
試験性 *-- 安定性
試験性 *-- 理解容易性

object スピード
object リスク
実行円滑性 -- スピード
実行円滑性 -- リスク

object 観測点
object 追跡性
観測容易性 -- 観測点
観測容易性 -- 追跡性

object 制御点
制御容易性 -- 制御点

object 結合度
分解容易性 -- 結合度

object 凝集度
object リーダブル
単純性 -- 凝集度
単純性 -- リーダブル

object 安定度
object 決定性
安定性 -- 安定度
安定性 -- 決定性

object ドキュメント
理解容易性 -- ドキュメント
理解容易性 -- 凝集度
理解容易性 -- リーダブル

object テストケースの数
object 外部環境への依存
スピード -- テストケースの数
スピード -- 外部環境への依存

object テスト環境
リスク -- テスト環境

object インターフェース
観測点 -- インターフェース
制御点 -- インターフェース

object ロギング
追跡性 -- ロギング

object 依存性逆転
結合度 -- 依存性逆転
安定度 -- 依存性逆転

object 依存性の注入
決定性 -- 依存性の注入

object グループ化
凝集度 -- グループ化
@enduml
