@startuml 投資信託のモデル
object ファンド
object ポートフォリオ
object 金融資産
ファンド -- ポートフォリオ
ポートフォリオ *-- 金融資産

object 基準価格
note top: 1日に1つ算出される
基準価格 - ファンド

object 販売会社
object 売買
object 投資家
売買 "*" -- "1" ファンド
売買 "*" -- "1" 販売会社
投資家 "1" -- "*" 売買

object 運用会社
販売会社 -- 運用会社: 仲介
ファンド -- 運用会社: 運用

object 信託銀行
運用会社 - 信託銀行: 運用指図
金融資産 - 信託銀行: 管理
@enduml
